# Generated by Django 2.0.13 on 2019-04-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20190429_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='update_at',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='created_at',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='update_at',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='created_at',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='update_at',
            new_name='update_time',
        ),
    ]
