# Generated by Django 2.0.13 on 2019-05-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-create_time']},
        ),
    ]
